services:
  - type: web
    name: bitsafe-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    rootDirectory: server
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3001
